env:
- _PYGITHUB=1.26.0 _PYYAML=3.11
- _PYGITHUB=1.26.0 _PYYAML=3.12
- _PYGITHUB=1.27.1 _PYYAML=3.11
- _PYGITHUB=1.27.1 _PYYAML=3.12
- _PYGITHUB=1.29 _PYYAML=3.11
- _PYGITHUB=1.29 _PYYAML=3.12
- _PYGITHUB=1.31 _PYYAML=3.11
- _PYGITHUB=1.31 _PYYAML=3.12
- _PYGITHUB=1.32 _PYYAML=3.11
- _PYGITHUB=1.32 _PYYAML=3.12
- _PYGITHUB=1.33 _PYYAML=3.11
- _PYGITHUB=1.33 _PYYAML=3.12
- _PYGITHUB=1.34 _PYYAML=3.11
- _PYGITHUB=1.34 _PYYAML=3.12
- _PYGITHUB=1.35 _PYYAML=3.11
- _PYGITHUB=1.35 _PYYAML=3.12
- _PYGITHUB=1.36 _PYYAML=3.11
- _PYGITHUB=1.36 _PYYAML=3.12
install:
- pip install coverage flake8 mock PyYAML==$_PYYAML PyGithub==$_PYGITHUB
- pip install https://github.com/PyCQA/astroid/zipball/master https://github.com/PyCQA/pylint/zipball/master
language: python
python:
- 2.7
- 3.5
script:
- ./test.sh
